version: '3.5'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    volumes:
      # copy the sql script to create tables
      - ./sql/init-data.sql:/docker-entrypoint-initdb.d/init.sql