-- Creation of User table
CREATE TABLE IF NOT EXISTS USERS (
  USER_ID INT NOT NULL,
  USERNAME varchar(250) NOT NULL,
  PASSWORD varchar(250) NOT NULL,
  PRIMARY KEY (USER_ID)
);

-- Creation of Permissions table
CREATE TABLE IF NOT EXISTS PERMISSIONS (
  PERMISSION_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  PERMISSION_NAME varchar(250) NOT NULL,
  PRIMARY KEY (PERMISSION_ID)
);

-- Creation of BlockedUsers table
CREATE TABLE IF NOT EXISTS BLOCKED_USERS (
  BLOCKED_USER_ID INT NOT NULL,
  USERNAME varchar(250) NOT NULL,
  BLOCKED_TIME TIMESTAMP NOT NULL,
  PRIMARY KEY (BLOCKED_USER_ID)
);

--create sequence for sql inserts
CREATE SEQUENCE hibernate_sequence START 1;

-- Filling of USERS
INSERT INTO USERS(USER_ID, USERNAME, PASSWORD)
VALUES ('1', 'user_1', '$2a$10$98ruQicinQKqDoB4uNQ9IO/2.b2lKsx7Fh8SnhueHa22Fi93Vpj3q'); --password is "user_1"

INSERT INTO USERS(USER_ID, USERNAME, PASSWORD)
VALUES ('2', 'user_2', '$2a$10$3Vw/nvjnlQSgA2TEIYzBBe2d6yIJGgw5T9.f22igajNaGBV1lmMYy'); --password is "user_2"

INSERT INTO USERS(USER_ID, USERNAME, PASSWORD)
VALUES ('3', 'user_3', '$2a$10$4NCwANfEf7LUDttGYpy5FecIyM8m426OaZ.2uBSycRUxOA4AO2zCC'); --password is "user_3"


-- Filling of Permissions
INSERT INTO PERMISSIONS(PERMISSION_ID, USER_ID, PERMISSION_NAME)
VALUES ('1', '1', 'VIEW_INFO');

INSERT INTO PERMISSIONS(PERMISSION_ID, USER_ID, PERMISSION_NAME)
VALUES ('2', '2', 'VIEW_ADMIN');

INSERT INTO PERMISSIONS(PERMISSION_ID, USER_ID, PERMISSION_NAME)
VALUES ('3', '3', 'VIEW_INFO');
INSERT INTO PERMISSIONS(PERMISSION_ID, USER_ID, PERMISSION_NAME)
VALUES ('4', '3', 'VIEW_ADMIN');
